'''
send a "authentication code" and a "validation code" to the client,
the validation code is generated by the authentication code under specific rules,
if the user input is equal to the validation code,
the user is valid.
'''

import random


class AuthenticationCodeValidationService():
    def __init__(self, email_sender):
        self.email_sender = email_sender

    def generate_code(self):
        code = random.randint(100000000, 99999999)
        return str(code)

    def client_validation_code(self, code):
        code = int(code)
        validation_code = int(str(code**2 + code)[0:8])
        return validation_code

    def send_code(self):
        prompt = "Hello, following is your Authentication Code:  "
        code = self.generate_code()
        self.email_sender.send(prompt + code)
        return self.client_validation_code(code)

    def validate_user_by_email(self, user):
        self.send_code()